export default [
    "Do you know why you're here ?",
    "...",
    "You really have no clue..",
    "I knew it.",
    "Well since you're here, let's try something.",
    "The rules are simple.",
    "I give you a choice.",
    "You choose a door depending on your decision.",
    "Got it ?",
    "Let's start with an easy one, ok ?",
    "...",
    "Do you believe in god ?",
    "Do you believe in god ?",
    "Right, interesting..",
    "I thought you would answer that..",
    "Alright do you see this bar below ?",
    "It represents morality.",
    "If you take a 'moral' decision, it will go up..",
    "If you take a 'moral' decision, it will go up..",
    ".. But if you take a 'bad' decision, it will go down.",
    ".. But if you take a 'bad' decision, it will go down.",
    "Let's play, shall we ?",
    "Let's play, shall we ?"
]